version: '3.8'

# ملف Docker Compose بسيط للنشر السريع
services:
  sharelatex:
    image: sharelatex/sharelatex:latest
    container_name: overleaf-app
    restart: unless-stopped
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "80:80"
    volumes:
      - sharelatex_data:/var/lib/overleaf
    environment:
      OVERLEAF_APP_NAME: "Overleaf Community Edition"
      OVERLEAF_MONGO_URL: mongodb://mongo/sharelatex
      OVERLEAF_REDIS_HOST: redis
      REDIS_HOST: redis
      ENABLED_LINKED_FILE_TYPES: 'project_file,project_output_file'
      ENABLE_CONVERSIONS: 'true'
      EMAIL_CONFIRMATION_DISABLED: 'true'
      OVERLEAF_SITE_URL: ${OVERLEAF_SITE_URL:-http://localhost}
      OVERLEAF_ADMIN_EMAIL: ${OVERLEAF_ADMIN_EMAIL:-admin@example.com}

  mongo:
    image: mongo:6.0
    container_name: overleaf-mongo
    restart: unless-stopped
    command: '--replSet overleaf'
    volumes:
      - mongo_data:/data/db
      - ./bin/shared/mongodb-init-replica-set.js:/docker-entrypoint-initdb.d/mongodb-init-replica-set.js
    environment:
      MONGO_INITDB_DATABASE: sharelatex
    extra_hosts:
      - mongo:127.0.0.1
    healthcheck:
      test: echo 'db.stats().ok' | mongosh localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:6.2-alpine
    container_name: overleaf-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  sharelatex_data:
  mongo_data:
  redis_data:
